const $ = (id) => document.getElementById(id);
let operators = [];
let selected = null;

function uid(){
  const d = new Date();
  return 'slop-' + d.toISOString().replace(/[-:.TZ]/g,'').slice(0,14);
}
function val(id){ return $(id).value.trim(); }

async function loadOperators(){
  try{
    const r = await fetch('../machine/operators.json');
    const data = await r.json();
    operators = data.operators || [];
    renderOperators();
  }catch(e){
    $('operators').textContent = 'Could not load ../machine/operators.json. Serve the repo over HTTP instead of opening index.html directly.';
  }
}
function renderOperators(){
  const q = val('operatorSearch').toLowerCase();
  const rows = operators.filter(o =>
    !q || [o.id,o.name,o.class,o.summary].join(' ').toLowerCase().includes(q)
  );
  $('operators').innerHTML = rows.map(o => `
    <div class="op ${selected?.id===o.id?'active':''}" data-id="${o.id}">
      <b>${o.name}</b>
      <small>${o.class} · ${o.status}</small>
    </div>`).join('');
  [...document.querySelectorAll('.op')].forEach(el => el.onclick = () => {
    selected = operators.find(o => o.id === el.dataset.id);
    renderOperators();
    $('operatorDetail').innerHTML = selected
      ? '<b>'+selected.id+'</b><br>'+selected.summary
      : '';
  });
}
function buildRun(doseOverride=null){
  const dose = doseOverride ?? Number($('strength').value);
  return {
    run_id: uid(),
    date: new Date().toISOString(),
    researcher: null,
    media: $('media').value,
    model_or_tool: val('model') || 'UNSPECIFIED',
    model_version: null,
    operator_ids: selected ? [selected.id] : [],
    epistemic_status_before: 'HYPOTHESIS',
    input_or_seed_material: null,
    seed_or_randomness: null,
    reference_assets: [],
    assumption_attacked: val('assumption'),
    mechanism_claim: null,
    competing_conditions: [val('condA'), val('condB')].filter(Boolean),
    invariant_or_anchor: val('anchor') || null,
    procedure: val('procedure'),
    baseline: null,
    control: null,
    ablation: null,
    independent_variable: 'dose_or_strength',
    dose_or_strength: dose,
    iteration_or_cycle: 1,
    operation_order: selected ? [selected.id] : [],
    expected_artifact_family: val('expected') || null,
    condition_dropout_risk: val('dropout') || null,
    known_confounds: [],
    observed_result: 'UNRUN',
    artifact_coordinates_or_timestamps: null,
    persistence_after_cause_removed: null,
    route_or_history_effect: null,
    creative_utility: null,
    mechanism_confidence: null,
    next_test: null,
    notes: 'Generated by DAVID LAB v0.1'
  };
}
function showRun(){
  $('output').textContent = JSON.stringify(buildRun(), null, 2);
}
function makeSweep(){
  const c = Number($('strength').value);
  const pts = [-.2,-.1,0,.1,.2].map(x => Math.max(0,Math.min(1,Math.round((c+x)*100)/100)));
  $('sweep').innerHTML = pts.map((p,i)=>`
    <div class="dose"><span>${i===2?'CENTER':'DOSE'}</span><strong>${p.toFixed(2)}</strong></div>`).join('');
}
function saveHistory(){
  const run = buildRun();
  const arr = JSON.parse(localStorage.getItem('david_lab_runs') || '[]');
  arr.unshift(run);
  localStorage.setItem('david_lab_runs', JSON.stringify(arr.slice(0,100)));
  renderHistory();
  showRun();
}
function renderHistory(){
  const arr = JSON.parse(localStorage.getItem('david_lab_runs') || '[]');
  $('history').innerHTML = arr.length ? arr.map(r => `
    <div class="history-item">
      <b>${r.run_id}</b> · ${r.media} · ${r.operator_ids.join(', ') || 'no operator'} · dose ${r.dose_or_strength}
      <div class="muted">${r.assumption_attacked || 'no assumption recorded'}</div>
    </div>`).join('') : '<span class="muted">No saved runs yet.</span>';
}
function reset(){
  ['model','anchor','assumption','condA','condB','procedure','expected','dropout'].forEach(id => $(id).value='');
  selected = null; $('strength').value=.5; $('strengthValue').textContent='0.50'; $('output').textContent='{}'; $('sweep').innerHTML='';
  renderOperators();
}
$('operatorSearch').addEventListener('input',renderOperators);
$('strength').addEventListener('input',()=> $('strengthValue').textContent = Number($('strength').value).toFixed(2));
$('build').onclick = showRun;
$('makeSweep').onclick = makeSweep;
$('save').onclick = saveHistory;
$('newRun').onclick = reset;
$('copy').onclick = async () => {
  showRun();
  await navigator.clipboard.writeText($('output').textContent);
  $('copy').textContent='COPIED';
  setTimeout(()=>$('copy').textContent='COPY JSON',900);
};
loadOperators();
renderHistory();